name: Truffle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS 14
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Show NodeJS version    
      run: npm --version
    
    - name: Install Truffle
      run: npm install truffle -g
    
    - name: Install Truffle Dependencies
      run: npm install      
    
    - name: Run Truffle Test with CI=true for Codechecks  
      run: CI=true truffle test

    - name: Run Codechecks
      run: npx codechecks
      env:
        CC_SECRET: ${{ secrets.CC_SECRET }}  
    
    - name: Run Test Coverage
      run: truffle run coverage
    
    - name: Generate .coveralls.yml file
      run: echo "${{ secrets.DOT_COVERALLS_YML }}" > .coveralls.yml
      
    - name: Send Coverage Info to CoverAlls
      run: cat coverage/lcov.info | npx coveralls
    
    - name: Setup Python 3.8  
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Show Python version
      run: python --version
    
    - name: Clone SmartBugs Repo
      run: git clone https://github.com/smartbugs/smartbugs.git
    
    - name: Remove SmartBugs Results and Install SmartBugs Dependencies
      run: |
        cd smartbugs
        rm -r results
        pip install -r requirements.txt

    - name: Run SmartBugs Analysis
      run: |
        solidityFiles=($(ls -I Migrations.sol contracts))
        DIR=$(pwd);cd smartbugs
        for sol in "${solidityFiles[@]}"
        do
          echo "Analysing $sol..."
          python smartBugs.py --tool all --file $DIR/contracts/$sol --unique-sarif-output output.sarif
        done
           
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: output.sarif
        category: smartbug