name: Truffle Unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS 14
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Show NodeJS version    
      run: npm --version
    
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Truffle
      run: npm install truffle -g
    
    - name: Install Truffle Dependencies
      run: npm install      
    
    - name: Run Truffle Test with CI=true for Codechecks  
      run: truffle test --show-events
      env:
        CI: true

    - name: Run Codechecks
      run: npx codechecks
      env:
        CC_SECRET: ${{ secrets.CC_SECRET }}  
    
    - name: Run Test Coverage
      run: truffle run coverage
      env:
        CI: true
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
        flag-name: unit